function [scenario, egoVehicle, waypoints,speed] = createDrivingScenarioElliptical()
%%%%%% This is an exmaple function for WaypointsInter function.%%%%%%


% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 24.2 (R2024b) and Automated Driving Toolbox 24.2 (R2024b).
% Generated on: 29-Sep-2025 13:00:08

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 0.2 0;
    120 0.2 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

roadCenters = [0 -80.8 0;
    120 -80.8 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road2');

roadCenters = [5.97 0.37 0;
    -64.74 -40.15 0;
    9 -80.76 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road3');

roadCenters = [110 0.2 0;
    178.7 -38.8 0;
    110.9 -81 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road1');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [0 -1.9 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [0 -1.9 0;
    8.9 -1.9 0;
    18 -1.9 0;
    30.1 -1.9 0;
    63 -1.9 0;
    92.1 -1.5 0;
    116.1 -1.5 0;
    123.18 -1.76 0.01;
    130.3 -2.5 0.01;
    137.72 -3.49 0.01;
    142.8 -4.7 0.01;
    149.92 -6.75 0.01;
    155.88 -9.33 0.01;
    161.17 -12.34 0.01;
    168.14 -18.11 0.01;
    172.83 -24.13 0.01;
    175.13 -29.24 0.01;
    176.57 -34.41 0.01;
    176.93 -38.56 0.01;
    176.81 -42.05 0.01;
    176.27 -45.78 0.01;
    174.53 -51.31 0.01;
    171.77 -56.18 0.01;
    169.6 -59.25 0.01;
    167.13 -62.13 0.01;
    164.31 -64.72 0.01;
    161.3 -67.18 0.01;
    158.05 -69.23 0.01;
    152.94 -71.81 0.01;
    149.28 -73.3 0.01;
    145.55 -74.57 0.01;
    140.01 -76.01 0.01;
    133.94 -77.21 0.01;
    128.35 -77.99 0.01;
    120.66 -78.78 0.01;
    109.95 -79.32 0;
    92.09 -79.26 0;
    58.06 -78.9 0;
    38 -78.89 0;
    12 -79 0;
    7.94 -79.02 0.01;
    2.29 -79.05 0.01;
    -1.1 -79 0.01;
    -6.93 -79.01 0.01;
    -13.3 -78.88 0.01;
    -19.36 -78.34 0.01;
    -26.36 -77.13 0.01;
    -31.95 -75.5 0.01;
    -37.38 -73.61 0.01;
    -41.01 -71.95 0.01;
    -44.38 -70.3 0.01;
    -47.83 -67.96 0.01;
    -51.19 -65.09 0.01;
    -54.73 -61.55 0.01;
    -57.83 -57.29 0.01;
    -60.64 -52.2 0.01;
    -62.16 -48.42 0.01;
    -62.97 -44.2 0.01;
    -62.97 -39.22 0.01;
    -62.07 -33.75 0.01;
    -60.19 -28.22 0.01;
    -57.72 -23.19 0.01;
    -54.01 -18.85 0.01;
    -49.92 -14.76 0.01;
    -45.39 -11.44 0.01;
    -38.49 -7.68 0.01;
    -31.31 -4.95 0.01;
    -25.39 -3.78 0.01;
    -19.69 -2.88 0.01;
    -13.96 -2.17 0.01;
    -8.08 -1.85 0.01;
    -2.79 -1.7 0.01;
    0 -1.9 0.01];
speed = [30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30;30];
waittime = [0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0];
trajectory(egoVehicle, waypoints, speed, waittime);

